# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

mapping <- function(ascii_letter) {
    .Call('_tabseq_mapping', PACKAGE = 'tabseq', ascii_letter)
}

kmer_count <- function(sequence_R) {
    .Call('_tabseq_kmer_count', PACKAGE = 'tabseq', sequence_R)
}

rcpp_hello_world <- function() {
    .Call('_tabseq_rcpp_hello_world', PACKAGE = 'tabseq')
}

special_test <- function() {
    .Call('_tabseq_special_test', PACKAGE = 'tabseq')
}

